### ISSUE TITLE
dmap/lsdev not showing drive info in Houston UI

### ISSUE THREAD

**Issue by mmcphee** [45Drives/tools#24]
A user is reporting slots showing as having a ssd+caddy when they have (from what they can tell) otherwise healthy drives in the slots.

![e1](https://user-images.githubusercontent.com/18193886/147672974-44772bd3-2568-441f-b4e7-84b3e3534e89.png)
![e2](https://user-images.githubusercontent.com/18193886/147672975-aad89d47-8262-4f41-b9d6-4e26e3577a4a.png)
[lsdevj.txt](https://github.com/45Drives/tools/files/7789372/lsdevj.txt)

**Comment by markdhooper** [comment]
I managed to re-create this issue after tossing a bunch of random hard drives into an xl60.
since I don't know exactly what the make and model of the malfunctioning drives were that we used in the unit your screenshots were from. 
![before](https://user-images.githubusercontent.com/50240103/149405517-5ecbb61f-7b05-419a-b276-ef5ce00127ef.png)

But I patched lsdev and managed to fix it, at least for the smattering of drives that I had.
![after](https://user-images.githubusercontent.com/50240103/149406794-a6c16994-6be0-4b0f-8a73-ed86c7289774.png)


If there are still issues, please provide me with the output of `smartctl -a /dev/(MALFUNCTIONING-DRIVE-ALAIS-HERE) --json`
My fix is about to be released to the stable repo so you should be able to just update via your package manager.
