### ISSUE TITLE
lsdev crashing when it tries to inspect smartctl json data

### ISSUE THREAD

**Issue by mmcphee** [45Drives/tools#25]
Customer updated tools to make use of the most recent lsdev update so that his disks would show up properly in the disks tab. After rebooting and attempting to access the disks tab again, he is presented with a python error.

Attached is a json file for the drives in the affected server. 

![image](https://user-images.githubusercontent.com/18193886/150587222-48aa63e9-ea2a-4688-bfea-ebb274ae6ef7.png)

![image](https://user-images.githubusercontent.com/18193886/150587269-6536d121-312c-4cee-9df0-f8abf5b0a499.png)

[bugreport_119370-5.zip](https://github.com/45Drives/tools/files/7916106/bugreport_119370-5.zip)
[bugreport_119370-5.txt](https://github.com/45Drives/tools/files/7916126/bugreport_119370-5.txt)

**Comment by markdhooper** [comment]
So I looked into it. 
The error you are getting is originating from drive 4-7.

If you look in the txt file you sent, you can see that "smart_status" isn't in there for 4-7. 
```
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      1
    ],
    "svn_revision": "5022",
    "platform_info": "x86_64-linux-5.4.0-96-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-a",
      "/dev/disk/by-path/pci-0000:b3:00.0-sas-phy5-lun-0",
      "--json"
    ],
    "messages": [
      {
        "string": "Smartctl open device: /dev/disk/by-path/pci-0000:b3:00.0-sas-phy5-lun-0 failed: No such device or address",
        "severity": "error"
      }
    ],
    "exit_status": 2
  }
}
```

the error message of:
"Smartctl open device: /dev/disk/by-path/pci-0000:b3:00.0-sas-phy5-lun-0 failed: No such device or address"

is odd because we can see that it is there in the output of `ls /dev/disk/by-path`

lsdev will only try running smartctl on devices that are present. So it's possible that there is something wrong with the drive in 4-7.

Either way, I made sure that the crash that you encountered here can't happen again. I patched it in the latest release of 45drives-tools (2.0.5-4)

Should be able to update using your package manager now.
